import { test,expect } from '@playwright/test';
import {mkdir} from 'node:fs/promises';
const shots='evidence/screenshots';
async function send(page,text){await page.locator('#message').fill(text);await page.locator('#send').click();await expect(page.locator('#pending')).toBeHidden();}
async function demo(page){await page.locator('#sample').click();await expect(page.locator('[data-statement="count1"]')).toContainText('8');}
test.beforeEach(async({page})=>{await page.goto('/');await expect(page.locator('#mode')).toHaveText('MOCK · NO MODEL CALLS');});
test('source stepper, text cues, value patch and local timer continuity',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await mkdir(shots,{recursive:true});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:shots+'/01-start.png',fullPage:true});await demo(page);
 await expect(page.locator('#spoken')).toContainText('current screen');await send(page,'next');await expect(page.locator('#position')).toHaveText('2 / 4');await page.getByRole('button',{name:'Start simulation',exact:true}).click();
 await page.locator('#next').click();await expect(page.locator('#position')).toHaveText('3 / 4');await page.locator('#back').click();await expect(page.locator('.timer-status')).toHaveText('running');
 await page.locator('#pause').click();await expect(page.locator('.timer-status')).toHaveText('paused');await expect(page.locator('#next')).toBeDisabled();await page.locator('#pause').click();await expect(page.locator('.timer-status')).toHaveText('running');
 await page.getByRole('button',{name:'Simulate finish',exact:true}).click();await expect(page.locator('.timer-status')).toHaveText('done');await expect(page.locator('#position')).toHaveText('2 / 4');
 await send(page,'change value to 6');await expect(page.locator('#position')).toHaveText('2 / 4');await send(page,'next');await expect(page.locator('[data-statement="count2"]')).toContainText('6');await page.screenshot({path:shots+'/02-workout-state.png',fullPage:true});expect(errors).toEqual([]);
});
test('repeated sends, interruption, reset while pending and post-reset navigation',async({page})=>{
 await page.locator('.builder').evaluate(e=>e.open=true);await page.locator('#fault').selectOption('slow');await page.locator('#message').fill('/demo');await page.locator('#send').click();await page.locator('#message').fill('/demo');await page.locator('#send').click();await expect(page.locator('.message.user')).toHaveCount(1);await page.locator('#reset').click();await page.waitForTimeout(2500);await expect(page.locator('#screen')).toContainText('Your workout starts here');await demo(page);await page.locator('#next').click();await page.locator('#reset').click();await demo(page);await page.locator('#next').click();await expect(page.locator('#position')).toHaveText('2 / 4');
 await page.locator('#fault').selectOption('slow');await page.locator('#message').fill('next');await page.locator('#send').click();await send(page,'back');await expect(page.locator('#position')).toHaveText('1 / 4');
});
for(const fault of ['schema','request'])test(`${fault} failure preserves screen and retry recovers`,async({page})=>{await demo(page);await page.locator('.builder').evaluate(e=>e.open=true);await page.locator('#fault').selectOption(fault);await send(page,'next');await expect(page.locator('#error')).toBeVisible();await expect(page.locator('[data-statement="count1"]')).toContainText('8');await page.locator('#retry').click();await expect(page.locator('#position')).toHaveText('2 / 4');await expect(page.locator('#error')).toBeHidden();});
test('local valid/invalid patches are data and candidate component can be registered',async({page})=>{
 await demo(page);await page.locator('.builder').evaluate(e=>e.open=true);await page.locator('#patch').fill('count1 = Keyword("<img src=x onerror=alert(1)>", "inert")');await page.locator('#apply-patch').click();await expect(page.locator('[data-statement="count1"]')).toContainText('<img src=x');await expect(page.locator('#screen img')).toHaveCount(0);
 await page.locator('#patch').fill('count1 = Function("evil")');await page.locator('#apply-patch').click();await expect(page.locator('#patch-status')).toContainText('Invalid patch');
 // Trusted test code registers a candidate component in all three local seams.
 await page.evaluate(async()=>{const {OPENUI_LIBRARY}=await import('/shared/openui/openui-library.js');const {propValidators}=await import('/shared/openui/validate.js');const {renderers}=await import('/web/components.js');OPENUI_LIBRARY.StatusPill={args:['label','value'],required:2};propValidators.StatusPill=p=>typeof p.label==='string'&&typeof p.value==='string';renderers.StatusPill=({props:p})=>{const n=document.createElement('div');n.textContent=p.label+': '+p.value;return n;};});
 await page.locator('#patch').fill('page1 = Screen([heading1, custom1])\ncustom1 = StatusPill("Sample", "A")');await page.locator('#apply-patch').click();await expect(page.locator('[data-statement="custom1"]')).toHaveText('Sample: A');
});
test('manual export contains screen/events/versions and no token; mobile fits',async({page})=>{
 await page.setViewportSize({width:390,height:844});await demo(page);await page.locator('.builder').evaluate(e=>e.open=true);await page.locator('#note').fill('Tested mock only. TOKEN=do-not-export');const download=page.waitForEvent('download');await page.locator('#export').click();const d=await download;const stream=await d.createReadStream();let content='';for await(const chunk of stream)content+=chunk;const json=JSON.parse(content);expect(json.state.ui_state).toContain('root = Screens');expect(json.events.find(e=>e.result).result.versions.protocolHash).toHaveLength(64);expect(content).not.toContain('do-not-export');expect(content).not.toContain('X-Local-Token');await page.locator('.builder').evaluate(e=>e.open=false);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:shots+'/03-mobile.png',fullPage:true});
});
test('RunQuest: calendar, both decisions, ending and restart through Mock buttons',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));const click=async name=>{await page.locator('#screen').getByRole('button',{name,exact:true}).click();await expect(page.locator('#pending')).toBeHidden();};
 await page.locator('#runquest').click();await expect(page.locator('#screen h3')).toHaveText('Your Running Journey');
 await expect(page.locator('[data-statement="rq_s1_p1"]')).toHaveText('Two weeks ago, you decided to start running.');await expect(page.locator('[data-statement="rq_s1_history"]')).toHaveText('Your Running History');await expect(page.locator('[data-statement="rq_s1_period"]')).toHaveText('Your previous seven days');await expect(page.locator('[data-statement="rq_s1_note"]')).toContainText('Example running history for this interactive journey.');await expect(page.locator('#screen')).not.toContainText('Alex');
 const days=page.locator('[data-statement="rq_week"] li');await expect(days).toHaveCount(7);await expect(page.locator('[data-statement="rq_week"] li.marker-plus')).toHaveCount(3);await expect(page.locator('[data-statement="rq_week"] li.marker-minus')).toHaveText(['Tue\n—','Wed\n—','Fri\n—','Sun\n—'],{useInnerText:true});await expect(page.locator('[data-statement="rq_week"] li.marker-plus')).toHaveText(['Mon\n2.0 km','Thu\n3.0 km','Sat\n2.5 km'],{useInnerText:true});
 await expect(page.locator('[data-statement="rq_s1_totals"]')).toHaveText('Running days: 3 · Total distance: 7.5 km');expect(await page.locator('[data-statement="rq_week"]').evaluate(e=>getComputedStyle(e).display)).toBe('grid');
 await click('Start your journey');await expect(page.locator('#screen h3')).toHaveText('A New Week');await expect(page.locator('#navigation')).toBeHidden();await expect(page.locator('#progress span')).toHaveCount(0);
 await click('Stay Flexible');await expect(page.locator('#screen h3')).toHaveText('Where Did the Week Go?');
 await click('Continue');await expect(page.locator('#screen h3')).toHaveText('A Moment to Reflect');
 await click('Leave It for Another Time');await expect(page.locator('#screen h3')).toHaveText('Your Reflection');await expect(page.locator('#navigation')).toBeHidden();await expect(page.locator('[data-statement="rq_s5_p1"]')).toContainText('The week became busy before you found an opportunity');await expect(page.locator('[data-statement="rq_s5_choices"]')).toContainText('First decision: Stay Flexible');
 await click('Try Another Journey');await expect(page.locator('#screen h3')).toHaveText('Your Running Journey');await expect(page.locator('#navigation')).toBeHidden();expect(await page.locator('#state-json').textContent()).not.toContain('rq_c1');expect(errors).toEqual([]);
});
test('non-RunQuest lists with plus/minus markers keep default rendering and fixture stepper',async({page})=>{
 await demo(page);await page.locator('.builder').evaluate(e=>e.open=true);await page.locator('#patch').fill('page1 = Screen([heading1, count1, note1, cue1, pros1])\npros1 = List([pro1, con1])\npro1 = ListItem("Upside", "plus")\ncon1 = ListItem("Downside", "minus")');await page.locator('#apply-patch').click();
 const list=page.locator('[data-statement="pros1"]');await expect(list.locator('li')).toHaveCount(2);expect(await list.evaluate(e=>getComputedStyle(e).display)).toBe('block');expect(await list.locator('li').first().evaluate(e=>getComputedStyle(e).display)).toBe('list-item');
 await expect(page.locator('#navigation')).toBeVisible();await expect(page.locator('#progress span')).toHaveCount(4);await expect(page.locator('#position')).toHaveText('1 / 4');
});
test('runtime starts mock; Codex blocked; selecting never calls model endpoint',async({page})=>{let turns=0;page.on('request',r=>{if(r.url().includes('/api/turn'))turns++;});await page.locator('#provider').selectOption('codex-cli');await expect(page.locator('#send')).toBeDisabled();await expect(page.locator('#provider-description')).toContainText('no-command/no-private-read');expect(turns).toBe(0);});
test('configured CLI needs explicit consent and records fake provider identity',async({page})=>{
 await page.route('**/api/config',async route=>{const response=await route.fetch();const cfg=await response.json();cfg.providers.find(p=>p.id==='claude-cli').enabled=true;await route.fulfill({json:cfg});});await page.reload();await page.locator('#provider').selectOption('claude-cli');await expect(page.locator('#send')).toBeDisabled();await page.locator('#consent').check();await page.route('**/api/turn',route=>route.fulfill({json:{turn:{reply:'Transport fixture, not a live CLI request.'},versions:{provider:'claude-cli',mode:'live',model:'fixture-only'}}}));await send(page,'hello');await expect(page.locator('#spoken')).toContainText('Transport fixture');
});
